# Copyright (C) 2026 - Bharadwaj Raman - https://github.com/nba1990/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License v3.
#
# See the LICENSE file for details.

from __future__ import annotations

from pathlib import Path

import streamlit as st

from src.config import get_app_ui_config
from src.sroi_charts.sroi_figures import (
    make_alignment_heatmap_figure,
    make_framework_flow_plotly_figure,
    make_funding_flows_figure,
    make_measurement_gap_figure,
    make_nlcf_wales_figure,
    make_sroi_comparison_figure,
    make_timeline_figure,
    make_volunteering_value_figure,
    make_wcva_wg_funding_figure,
)


@st.cache_data
def _get_mindmap_html() -> str:
    """Load the SROI mind-map HTML once per process; avoids repeated disk reads."""
    root = Path(__file__).resolve().parent.parent.parent
    path = (
        root
        / "references/SROI_Wales_Voluntary_Sector/docs/WCVA_Text_Interactive_MindMap.html"
    )
    return path.read_text(encoding="utf-8")


def render_sroi_references() -> None:
    """Render the SROI & References page: evidence charts and embedded mind-map.

    Uses get_app_ui_config() for palette_mode and text_scale; no DataFrame required.
    """

    st.title("SROI & References — Welsh Voluntary Sector")

    st.markdown(
        "This page summarises the **evidence base** on the economic and social value of "
        "the voluntary sector in Wales, with interactive charts drawn from this [SROI "
        "briefing and related reference material]"
        "(https://nextclouds.webo.hosting/s/Cjmb8wn55JLPGCs?dir=/&editing=false&openfile=true)."
    )

    st.header(
        "1. Headline [SROI](https://www.socialvalueint.org/guide-to-sroi) and Scale"
    )

    # Show SROI definition (short).
    with st.expander("What is SROI?"):
        st.markdown(
            "- Social Return on Investment (SROI) is an evaluation framework designed to measure the social, "
            "environmental and economic value generated by an intervention by assigning monetary proxies to outcomes "
            "experienced by stakeholders.\n"
            "- Developed in the UK and widely used in the voluntary sector, the approach builds on cost-benefit analysis "
            "but aims to capture forms of value that are typically excluded from conventional financial accounting "
            "(Nicholls et al., 2012; Social Value UK).\n"
        )

    st.markdown(
        "- **Every £1 invested** in community-based voluntary activity in Wales generates "
        "between roughly **£1.40 and £6.05** in measurable social value, depending on "
        "the programme and methodology.\n"
        "- **Unpaid carers in Wales** contribute an estimated **£8.1 billion per year** "
        "to the economy, while formal volunteering across England and Wales is valued at "
        "between **£3.8–£5.6 billion** per year at replacement cost.\n"
        "- There are about **47,116 active voluntary organisations in Wales**, but only "
        "around **8,000 registered charities**, leaving an estimated **39,000+ groups** "
        "largely invisible in official datasets."
    )

    # Show all references.
    with st.expander("Show all references to these headline figures"):
        st.markdown(
            "#### All References:\n"
            "- [Third sector scheme annual report 2023 to 2025 [HTML] | GOV.WALES]"
            "(https://www.gov.wales/third-sector-scheme-annual-report-2023-2025-html)\n"
            "- [Unpaid carers in Wales]"
            "(https://www.lukeclements.co.uk/unpaid-carers-in-wales/)\n"
            "- [The key priorities for carers in Wales - NHS Confederation]"
            "(https://www.nhsconfed.org/system/files/media/Key-priorities-carers-Wales.pdf)\n"
            "- [Third Sector Trends in England and Wales 2025: People, work, ambition]"
            "(https://www.philanthropy-impact.org/resource-hub-articles/third-sector-trends-in-england-and-wales-2025-"
            "people-work-ambition-and-impact/)\n"
            "- [Putting a value on sport's contribution to Wales]"
            "(https://www.sport.wales/extra-time-dec-2023/sroi/)\n"
            "- [Social Return on Investment of Sport in Wales]"
            "(https://www.sport.wales/research-and-insight/social-return-on-investment/)\n"
            "- [Third Sector Trends in England and Wales 2025 - St Chad's College]"
            "(https://www.stchads.ac.uk/wp-content/uploads/2025/12/Third-Sector-Trends-in-England-and-Wales-people-work"
            "-ambition-and-impact-December-2025.pdf)\n"
            "- [WCVA Annual Report 1934 - 1935]"
            "(https://wiserd.ac.uk/wp-content/uploads/wcva_annualreport_1934-1935.pdf)\n"
            "- [WCVA - 218093]"
            "(https://register-of-charities.charitycommission.gov.uk/en/charity-search/-/charity-details/218093)\n"
            "- [Witness Name: Ruth Marks - COVID 19 Inquiry]"
            "(https://covid19.public-inquiry.uk/wp-content/uploads/2023/07/21173118/INQ000177813-1.pdf)\n"
            "- [Annual Report on the Third Sector Scheme - gov.wales]"
            "(https://www.gov.wales/sites/default/files/publications/2021-06/third-sector-report-2020.pdf)\n"
            "- [KEY DATA - WCVA DATA HUB 2020]"
            "(https://wcva.cymru/wp-content/uploads/2020/04/2020-data-hub-update-E.pdf)\n"
            "- [Mapping-of-fundraising-by-the-voluntary-sector-in-Wales]"
            "(https://wcva.cymru/wp-content/uploads/2022/07/Mapping-of-fundraising-by-the-voluntary-sector-in-Wales-"
            "1.pdf)\n"
            "- [National survey shows trends in voluntary and community]"
            "(https://cvalive.org.uk/news/2025/national-survey-shows-trends-i/)\n"
            "- [Third Sector Trends in England and Wales 2025]"
            "(https://www.3sg.org.uk/post/third-sector-trends-in-england-and-wales-2025)\n"
            "- [17 March 2025 - Gov Wales]"
            "(https://www.gov.wales/sites/default/files/publications/2025-03/atisn24397.pdf)\n"
            "- [The National Lottery Community Fund - Annual Report - GOV.UK]"
            "(https://assets.publishing.service.gov.uk/media/66acc14e49b9c0597fdb0a0b/The_National_Lottery_Community_"
            "Fund_annual_report_and_accounts_2023_to_2024.pdf)\n"
            "- [Reflecting on 2024: A year of impact and community resilience]"
            "(https://bigblogwales.org.uk/2025/01/01/reflecting-on-2024-a-year-of-impact-and-community-resilience/)\n"
            "- [National Lottery Community Fund's grants up by over £80m last year]"
            "(https://www.civilsociety.co.uk/news/national-lottery-community-fund-s-grants-up-by-over-80m-last-year-"
            "accounts-show.html)\n"
            "- [North Wales Shared Prosperity Fund | Mantell Gwynedd]"
            "(https://mantellgwynedd.com/eng/shared-prosperity-fund.html)\n"
            "- [Shared Prosperity Fund: lessons learned survey report]"
            "(https://www.gov.wales/shared-prosperity-fund-lessons-learned-survey-report-html)\n"
            "- [WCVA works with a range of national specialists]"
            "(https://wcva.cymru/wp-content/uploads/2020/05/Wales-and-the-shared-prosperity-fund-e.pdf)\n"
            "- [WCVA Active Inclusion Fund Evaluation]"
            "(https://wcva.cymru/wp-content/uploads/2023/08/WCVA-Active-Inclusion-Fund-Evaluation-Final-Report-Executive-Summary.pdf)\n"
            "- [Social Return on Investment of Sport in Wales 2016/17]"
            "(https://wsa.wales/wp-content/uploads/dlm_uploads/V3-Sport-Wales-Report-1-SROI.pdf)\n"
            "- [Infoengine: Cyfle Cymru - Peer Mentoring Service]"
            "(https://en.infoengine.cymru/organisations/cyfle-cymru-peer-mentoring-service)\n"
            "- [Cyfle Cymru - Peer Mentoring Service - Infoengine]"
            "(https://en.infoengine.cymru/services/cyfle-cymru-peer-mentoring-service)\n"
            "- [North Wales Project | Mantell Gwynedd]"
            "(https://www.mantellgwynedd.com/eng/svc/north-wales-project.html)\n"
            "- [Cyfle Cymru Project Extended to March 2027 - Adferiad]"
            "(https://adferiad.org/cyfle-cymru-project-extended-to-march-2027/)\n"
            "- [Social Return on Investment of Nature-Based Activities for Adults with Mental Wellbeing Challenges]"
            "(https://www.mdpi.com/1660-4601/20/15/6500/pdf?version=1690950537)\n"
            "- [Executive summary - UK Civil Society Almanac 2024 - NCVO]"
            "(https://www.ncvo.org.uk/news-and-insights/news-index/uk-civil-society-almanac-2024/executive-summary/)\n"
            "- [Unpaid care in England and Wales]"
            "(https://www.carersuk.org/press-releases/unpaid-care-in-england-and-wales-valued-at-445-million-per-day/)\n"
            "- [Value of unpaid care in England and Wales now exceeds that of NHS budget]"
            "(https://centreforcare.ac.uk/updates/2023/05/valuing-carers/)\n"
            "- [Valuing Carers 2021]"
            "(https://www.carersuk.org/media/2d5le03c/valuing-carers-report.pdf)\n"
            "- [The Shared Prosperity and Levelling Up funds]"
            "(https://research.senedd.wales/research-articles/the-shared-prosperity-and-levelling-up-funds-what-s-the-"
            "latest/)\n"
            "- [Income sources - Financials | UK Civil Society Almanac 2024 - NCVO]"
            "(https://www.ncvo.org.uk/news-and-insights/news-index/uk-civil-society-almanac-2024/financials/"
            "where-do-voluntary-organisations-get-their-income-from/)\n"
            "- [Almanac shows charity sector income rose to £69bn]"
            "(https://www.civilsociety.co.uk/news/almanac-shows-charity-sector-income-rose-to-69bn-despite-government-"
            "funding-decline.html)\n"
            "- [Committees Parliament UK]"
            "(https://committees.parliament.uk/writtenevidence/70504/html/)\n"
            "- [Third sector scheme annual report 2023 to 2025 | GOV.WALES]"
            "(https://www.gov.wales/third-sector-scheme-annual-report-2023-2025-html)\n"
            "- [SROI - Review of the Technique]"
            "(https://www.researchgate.net/publication/328754594_Social_Return_on_Investment_SROI_a_review_of_the_technique)\n"
            "- [SROI - Approaches]"
            "(https://www.betterevaluation.org/methods-approaches/approaches/social-return-investment)\n"
            "- [SROI Calculator]"
            "(https://www.sopact.com/use-case/social-return-on-invesment-sroi)\n"
            "- [Guide to SROI]"
            "(https://www.executivecompass.co.uk/social-value-practice/resources/guide-to-measuring-social-return-on-investment-sroi/)\n"
        )

    # Show caveats about discrepancies between formal and informal volunteering and their methodological inconsistencies.
    with st.expander(
        "Show **caveats** and **discrepancies** between *formal* and *informal* volunteering and their "
        "**methodological inconsistencies**"
    ):
        st.markdown(
            "- **Some researchers have argued that survey-based estimates of volunteering, often used in national "
            "statistics, may be sensitive to how volunteering is defined and interpreted by respondents.**\n"
            "- **In the UK context, official statistics distinguish between *formal* volunteering (unpaid help given "
            "through groups, clubs or organisations) and *informal* volunteering (unpaid help given directly to "
            "individuals who are not relatives) *(DCMS, 2025; NCVO, 2023)*.**\n"
            "- **Because survey estimates depend on how respondents interpret these categories, researchers have "
            "highlighted challenges in consistently measuring voluntary activity, particularly where unpaid help falls "
            "outside organisational contexts *(Low et al., 2007; Fox, 2019)*.**\n"
            "- **Activities such as unpaid care for family members are therefore typically excluded from standard "
            "definitions of volunteering.**\n"
            "- **As a result, depending on how respondents interpret survey questions and classify their activities, "
            "some forms of unpaid contribution may be under-recorded, while others may be counted inconsistently.**\n"
            "- **This highlights broader methodological challenges in measuring voluntary effort and estimating the "
            "overall scale of volunteering activity.**\n"
        )

        st.markdown(
            "#### References:\n"
            "- [Gov UK - Volunteering & Charitable Giving]"
            "(https://www.gov.uk/government/statistics/community-life-survey-202425-annual-publication"
            "/community-life-survey-202425-volunteering-and-charitable-giving)\n"
            "- [NVCO - Volunteering]"
            "(https://www.ncvo.org.uk/news-and-insights/news-index/uk-civil-society-almanac-2023/volunteering/)\n"
            "- [City Research - Volunteering Survey]"
            "(https://openaccess.city.ac.uk/id/eprint/2547/1/Helping%20Out.pdf)\n"
            "- [UK Data Service - National Survey of Volunteering & Charitable Giving]"
            "(https://sp.ukdataservice.ac.uk/doc/5793/mrdoc/pdf/5793userguide.pdf)\n"
            "- [UK HLS - Volunteering & Its Consequences]"
            "(https://wiserd.ac.uk/wp-content/uploads/Volunteering-and-its-Consequences-using-UKHLS.pdf)\n"
            "- [Open University - Volunteering Definitions]"
            "(https://www.open.edu/openlearncreate/mod/oucontent/view.php?id=81610&section=1.2.1)\n"
            "- [Defining Who is a Volunteer: Conceptual and Empirical Considerations]"
            "(https://journals.sagepub.com/doi/10.1177/0899764096253006)\n"
            "- [Public Perception of: 'Who is a Volunteer']"
            "(https://repository.upenn.edu/entities/publication/6599e585-f602-4288-ae92-d4cbda43aa1d)\n"
        )

    ui_config = get_app_ui_config()
    palette_mode = ui_config.palette_mode
    text_scale = ui_config.text_scale or 1.0

    st.subheader("SROI ratios from key Wales-based studies")
    fig_sroi = make_sroi_comparison_figure(
        palette_mode=palette_mode, text_scale=text_scale
    )

    # IMPORTANT NOTE: `use_container_width` will be removed after 2025-12-31.
    # For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
    # Please replace `use_container_width` with `width`.

    st.plotly_chart(fig_sroi, width="stretch")

    st.subheader("Economic value of volunteering and unpaid care")
    fig_vol = make_volunteering_value_figure(
        palette_mode=palette_mode, text_scale=text_scale
    )
    st.plotly_chart(fig_vol, width="stretch")

    st.divider()

    st.header("2. Funding Architecture — Who Funds What?")
    st.markdown(
        "The Welsh voluntary sector is supported by a mix of **Welsh Government**, "
        "**National Lottery Community Fund (NLCF)**, **UK Shared Prosperity Fund (SPF)** "
        "and legacy **EU Structural Funds**, alongside charitable and earned income."
    )

    col_f1, col_f2 = st.columns(2)
    with col_f1:
        st.subheader("Estimated public funding flows")
        fig_funding = make_funding_flows_figure(
            palette_mode=palette_mode, text_scale=text_scale
        )
        st.plotly_chart(fig_funding, width="stretch")
    with col_f2:
        st.subheader("National Lottery Community Fund: Wales")
        fig_nlcf = make_nlcf_wales_figure(
            palette_mode=palette_mode, text_scale=text_scale
        )
        st.plotly_chart(fig_nlcf, width="stretch")

    st.subheader("Welsh Government payments to WCVA")
    fig_wcva = make_wcva_wg_funding_figure(
        palette_mode=palette_mode, text_scale=text_scale
    )
    st.plotly_chart(fig_wcva, width="stretch")

    st.divider()

    st.header("3. The Measurement Gap")
    st.markdown(
        "A central theme of the evidence briefing is the **measurement gap**: most "
        "grassroots organisations and a large share of informal voluntary activity are "
        "missing from standard statistics, even though they generate real value."
    )
    fig_gap = make_measurement_gap_figure(
        palette_mode=palette_mode, text_scale=text_scale
    )
    st.plotly_chart(fig_gap, width="stretch")

    st.divider()

    st.header("4. New Approach to Volunteering in Wales (2025)")
    st.markdown(
        "In 2025, Welsh Government and WCVA launched **A New Approach to Volunteering "
        "in Wales**, setting out a vision, delivery framework and implementation plan "
        "for volunteering up to 2030. The SROI evidence above underpins this framework."
    )

    st.subheader("Framework: Enablers → Objectives → Vision")
    fig_flow = make_framework_flow_plotly_figure(
        palette_mode=palette_mode, text_scale=text_scale
    )
    st.plotly_chart(fig_flow, width="stretch")

    st.subheader("Alignment between enablers and objectives")
    fig_align = make_alignment_heatmap_figure(
        palette_mode=palette_mode, text_scale=text_scale
    )
    st.plotly_chart(fig_align, width="stretch")

    st.subheader("Implementation timeline")
    fig_timeline = make_timeline_figure(
        palette_mode=palette_mode, text_scale=text_scale
    )
    st.plotly_chart(fig_timeline, width="stretch")

    st.header("5. Methodology & Caveats")
    st.markdown(
        "- **SROI is not an exact science**: Ratios depend on assumptions, proxy values "
        "and which outcomes are included. Different studies are not always directly "
        "comparable.\n"
        "- **Formal vs informal volunteering**: Official statistics often distinguish "
        "between *formal* volunteering (through organisations) and *informal* "
        "volunteering (unpaid help outside formal structures). Estimates are sensitive "
        "to how questions are asked and how respondents interpret them, so some unpaid "
        "contributions can be under-recorded or inconsistently counted.\n"
        "- **Invisible organisations**: Because many small or unregistered groups are "
        "missing from administrative data and surveys, their contribution to SROI and "
        "economic value is likely **understated**.\n"
        "- Where direct Wales-specific figures are not available, the briefing uses "
        "broader UK evidence and flags this clearly so that numbers are treated as "
        "indicative rather than precise for Wales."
    )

    st.markdown(
        "For full context, citations and methodological notes, see the [reference "
        "document](https://nextclouds.webo.hosting/s/Cjmb8wn55JLPGCs?dir=/&editing=false&openfile=true) "
        "and its associated sources."
    )

    st.divider()

    st.header("6. Additional References")

    html = _get_mindmap_html()
    st.components.v1.html(html, height=1920, scrolling=True)


# Source code available under AGPLv3: https://github.com/nba1990/wcva_data_analysis
